openapi: 3.0.0
info:
  title: educasia
  contact: {}
  version: '1.0'
servers:
- url: http://example.com
  variables: {}
paths:
  /users:
    get:
      tags:
      - users
      summary: list users
      operationId: listusers
      parameters:
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
    post:
      tags:
      - users
      summary: create one users
      operationId: createoneusers
      parameters:
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createoneusersrequest'
            example:
              nama: nama test
              email: test111@gmail.com
              no_hp: 085758612441
              jenis_kelamin: pria
              tanggal_lahir: 2020-12-15
              kelompok: kelas 2
              instansi: unsri ilkom
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /users/{userId}:
    get:
      tags:
      - users
      summary: get one users
      operationId: getoneusers
      parameters:
      - in: path
        name: userId
        required: true
        schema:
          type: integer
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
    put:
      tags:
      - users
      summary: update one users
      operationId: updateoneusers
      parameters:
      - in: path
        name: userId
        required: true
        schema:
          type: integer
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateoneusersrequest'
            example:
              nama: nama test edit
              email: test1@gmail.com
              no_hp: 085758612442
              tanggal_lahir: 2020-12-15
              kelompok: kelas 2
              instansi: unsri ilkom
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
    delete:
      tags:
      - users
      summary: delete one users
      operationId: deleteOneUsers
      parameters:
      - in: path
        name: userId
        required: true
        schema:
          type: integer
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /users/peserta:
    post:
      tags:
      - users
      summary: create one user+peserta
      operationId: createoneuser+peserta
      parameters:
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createoneuser%2Bpesertarequest'
            example:
              nama: namaku
              email: tesKategori2@gmail.com
              no_hp: 08888188111
              jenis_kelamin: pria
              tanggal_lahir: 1997-10-13
              kelompok: BB
              instansi: ilkom
              jadwal_test: 1
              jenis_test:
              - IST
              - MII
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /reset/test/{jadwalTestId}:
    delete:
      tags:
      - reset
      summary: reset seluruh peserta by id jadwaltest
      operationId: resetseluruhpesertabyidjadwaltest
      parameters:
      - in: path
        name: jadwalTestId
        required: true
        schema:
          type: integer
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /reset/peserta/{pesertaId}/subtest/{namaSubtest}:
    delete:
      tags:
      - reset
      summary: reset subtest peserta by id peserta dan code_subtest
      description: >-
        code_subtest = {

          subtest_1_ist, //start ist

          subtest_2_ist,

          subtest_3_ist,

          subtest_4_ist,

          subtest_5_ist,

          subtest_6_ist,

          subtest_7_ist,

          subtest_8_ist,

          subtest_9_ist, //end ist

          bagian_1_verb_ling, //start subtest mii

          bagian_2_log_math,

          bagian_3_spat,

          bagian_4_mus,

          bagian_5_bod_kin,

          bagian_6_inter,

          bagian_7_intra,

          bagian_8_nat, //end mii

        }
      operationId: resetsubtestpesertabyidpesertadancode_subtest
      parameters:
      - in: path
        name: pesertaId
        required: true
        schema:
          type: integer
      - in: path
        name: namaSubtest
        required: true
        schema:
          type: string
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /reset/peserta/{pesertaId}:
    delete:
      tags:
      - reset
      summary: reset satu peserta by id peserta
      description: reset seluruh subtest untuk satu peserta
      operationId: resetsatupesertabyidpeserta
      parameters:
      - in: path
        name: pesertaId
        required: true
        schema:
          type: integer
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /score-peserta/{jadwalTestId}:
    put:
      tags:
      - reset
      summary: reset score all peserta by id test
      operationId: resetscoreallpesertabyidtest
      parameters:
      - in: path
        name: jadwalTestId
        required: true
        schema:
          type: integer
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /score-peserta/{jadwalTestId}/{pesertaId}:
    put:
      tags:
      - reset
      summary: reset score one peserta by id test dan id peserta
      operationId: resetscoreonepesertabyidtestdanidpeserta
      parameters:
      - in: path
        name: jadwalTestId
        required: true
        schema:
          type: integer
      - in: path
        name: pesertaId
        required: true
        schema:
          type: integer
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /peserta/welcome-email/{pesertaId}/{emailPeserta}:
    post:
      tags:
      - email
      summary: send welcome-email peserta
      description: parameter pertama id jadwaltest, yang kedua email peserta
      operationId: sendwelcome-emailpeserta
      parameters:
      - in: path
        name: pesertaId
        required: true
        schema:
          type: integer
      - in: path
        name: emailPeserta
        required: true
        schema:
          type: string
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /peserta:
    get:
      tags:
      - peserta
      summary: get list peserta
      operationId: getlistpeserta
      parameters:
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
    post:
      tags:
      - peserta
      summary: create peserta
      operationId: createpeserta
      parameters:
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createpesertarequest'
            example:
              user_email:
              - aa@gmail.com
              - b@gmail.com
              - c@gmail.com
              - dd@gmail.com
              jadwal_test: 3
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /peserta/{pesertaId}:
    get:
      tags:
      - peserta
      summary: get one peserta by id
      description: >-
        return {

            "nama",

            "email",

            "no_hp",

            "tanggal_lahir",

            "kelompok",

            "instansi",

            "created_at",

            "updated_at",

            "deleted_at",

            "jenis_kelamin",

            "password",

            "valid",

            "expired",

            "jadwal_test",

        }
      operationId: getonepesertabyid
      parameters:
      - in: path
        name: pesertaId
        required: true
        schema:
          type: integer
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
    put:
      tags:
      - peserta
      summary: update data peserta by id
      description: request body sesuai dgn add user+peserta
      operationId: updatedatapesertabyid
      parameters:
      - in: path
        name: pesertaId
        required: true
        schema:
          type: integer
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updatedatapesertabyidrequest'
            example:
              nama: namaku
              email: tesKategori2@gmail.com
              no_hp: 08888188111
              tanggal_lahir: 1997-10-13
              kelompok: BB
              instansi: ilkom
              jenis_kelamin: pria
              password: ODUPWEWD
              valid: 2020-07-20T01:12:00Z
              expired: 2020-08-21T01:12:00Z
              jadwal_test: 1
              jenis_test:
              - IST
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
    delete:
      tags:
      - peserta
      summary: delete one peserta
      operationId: deleteonepeserta
      parameters:
      - in: path
        name: pesertaId
        required: true
        schema:
          type: integer
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /peserta/test/{jadwalTestId}:
    get:
      tags:
      - peserta
      summary: get list peserta by id jadwal_test
      operationId: getlistpesertabyidjadwal_test
      parameters:
      - in: path
        name: jadwalTestId
        required: true
        schema:
          type: integer
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /peserta/{pesertaId}/jawaban:
    get:
      tags:
      - peserta
      summary: show jawaban peserta
      description: get jawaban peserta by id peserta + query jenis tes
      operationId: showjawabanpeserta
      parameters:
      - in: path
        name: pesertaId
        required: true
        schema:
          type: integer
      - name: test
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: ist
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /jadwal-test:
    get:
      tags:
      - jadwal-test
      summary: list jadwal test
      operationId: listjadwaltest
      parameters:
      - name: date
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: boolean
          example: true
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
    post:
      tags:
      - jadwal-test
      summary: create jadwal test
      operationId: createjadwaltest
      parameters:
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createjadwaltestrequest'
            example:
              waktu: 2020-07-27 06:00
              expired: 2020-07-27 07:00
              instansi: testing 27
              keterangan: batch 1
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /jadwal-test/{jadwalTestId}:
    get:
      tags:
      - jadwal-test
      summary: get jadwal test
      operationId: getjadwaltest
      parameters:
      - in: path
        name: jadwalTestId
        required: true
        schema:
          type: integer
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
    put:
      tags:
      - jadwal-test
      summary: update jadwal test
      operationId: updatejadwaltest
      parameters:
      - in: path
        name: jadwalTestId
        required: true
        schema:
          type: integer
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updatejadwaltestrequest'
            example:
              waktu: 2020-07-19 10:00
              instansi: sma 9 testing
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
    delete:
      tags:
      - jadwal-test
      summary: delete jadwal test
      operationId: deletejadwaltest
      parameters:
      - in: path
        name: jadwalTestId
        required: true
        schema:
          type: integer
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /admin:
    get:
      tags:
      - admin
      summary: list admin
      operationId: listadmin
      parameters:
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
    post:
      tags:
      - admin
      summary: create admin
      operationId: createadmin
      parameters:
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createadminrequest'
            example:
              name: Admin for delete
              email: del@educasia.id
              password: 11111111
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /admin/{adminId}:
    get:
      tags:
      - admin
      summary: get admin
      operationId: getadmin
      parameters:
      - in: path
        name: adminId
        required: true
        schema:
          type: integer
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
    put:
      tags:
      - admin
      summary: update admin
      operationId: updateadmin
      parameters:
      - in: path
        name: adminId
        required: true
        schema:
          type: integer
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateadminrequest'
            example:
              name: Admin testcreate update
              email: bbc@educasia.id
              password: 12341234
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
    delete:
      tags:
      - admin
      summary: delete admin
      operationId: deleteadmin
      parameters:
      - in: path
        name: adminId
        required: true
        schema:
          type: integer
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /login:
    post:
      tags:
      - admin
      summary: login admin
      operationId: loginadmin
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/loginadminrequest'
            example:
              email: ana@educasia.id
              password: 12345678
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /admin/reset-password:
    post:
      tags:
      - admin
      summary: reset password admin by user
      operationId: resetpasswordadminbyuser
      parameters:
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/resetpasswordadminbyuserrequest'
            example:
              old_password: 1234567
              new_password: 12341234
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /peserta-test/{jadwalTestId}:
    get:
      tags:
      - export
      summary: export list peserta test
      operationId: exportlistpesertatest
      parameters:
      - in: path
        name: jadwalTestId
        required: true
        schema:
          type: integer
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /hasil-test/{jadwalTestId}:
    get:
      tags:
      - export
      summary: get hasil test
      description: /hasil-test/:id
      operationId: gethasiltest
      parameters:
      - in: path
        name: jadwalTestId
        required: true
        schema:
          type: integer
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /jawaban-test/{jadwalTestId}:
    get:
      tags:
      - export
      summary: get jawaban peserta dgn params id jadwal test
      operationId: getjawabanpesertadgnparamsidjadwaltest
      parameters:
      - in: path
        name: jadwalTestId
        required: true
        schema:
          type: integer
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /users/excel:
    post:
      tags:
      - import
      summary: import user by excel
      operationId: importuserbyexcel
      parameters:
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - user
              - jadwal_test
              type: object
              properties:
                user:
                  type: string
                jadwal_test:
                  type: integer
                  format: int32
                  example: 82
        required: false
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /soal/mii:
    get:
      tags:
      - Exam app
      summary: get one soal MII
      operationId: getonesoalMII
      parameters:
      - name: paket_soal
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: bagian_1_verb_ling
      - name: nomor
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 1
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /soal/ist:
    get:
      tags:
      - Exam app
      summary: get one soal IST
      operationId: getonesoalIST
      parameters:
      - name: paket_soal
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: subtest_1_ist
      - name: nomor
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 1
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /auth:
    post:
      tags:
      - Exam app
      summary: auth peserta
      operationId: authpeserta
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/authpesertarequest'
            example:
              email: jhon@gmail.com
              password: 12345678
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /time/ist:
    get:
      tags:
      - Exam app
      summary: get sisa waktu subtest
      operationId: getsisawaktusubtest
      parameters:
      - name: paket_soal
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: subtest_1_ist
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /jawaban:
    post:
      tags:
      - Exam app
      summary: submit jawaban
      operationId: submitjawaban
      parameters:
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/submitjawabanrequest'
            example:
              jawaban_peserta:
              - - 3
                - 5
              - - 2
                - 8
                - 0
              - - 2
                - 3
                - 5
              - - 2
                - 6
              - - 3
                - 0
              - - 7
                - 0
              - - 4
                - 5
              - - 4
                - 5
              - - 1
              - - 6
                - 7
              paket_soal: subtest_5_ist
              jenis_soal: ist
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /rincian-test:
    get:
      tags:
      - Exam app
      summary: get rincian tes
      operationId: getrinciantes
      parameters:
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /files:
    delete:
      tags:
      - Exam app
      summary: delete files in dir files
      operationId: deletefilesindirfiles
      parameters:
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /uploads:
    delete:
      tags:
      - Exam app
      summary: delete files in dir uploads
      operationId: deletefilesindiruploads
      parameters:
      - name: x-access-token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '{{token_api}}'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
components:
  schemas:
    createoneusersrequest:
      title: createoneusersrequest
      required:
      - nama
      - email
      - no_hp
      - jenis_kelamin
      - tanggal_lahir
      - kelompok
      - instansi
      - jenis_test
      type: object
      properties:
        nama:
          type: string
        email:
          type: string
        no_hp:
          type: string
        jenis_kelamin:
          type: string
        tanggal_lahir:
          type: string
        kelompok:
          type: string
        instansi:
          type: string
        jenis_test:
          type: string
      example:
        nama: nama test
        email: test111@gmail.com
        no_hp: 085758612441
        jenis_kelamin: pria
        tanggal_lahir: 2020-12-15
        kelompok: kelas 2
        instansi: unsri ilkom
        jenis_test: 'MII,IST'
    updateoneusersrequest:
      title: updateoneusersrequest
      required:
      - nama
      - email
      - no_hp
      - tanggal_lahir
      - kelompok
      - instansi
      type: object
      properties:
        nama:
          type: string
        email:
          type: string
        no_hp:
          type: string
        tanggal_lahir:
          type: string
        kelompok:
          type: string
        instansi:
          type: string
      example:
        nama: nama test edit
        email: test1@gmail.com
        no_hp: 085758612442
        tanggal_lahir: 2020-12-15
        kelompok: kelas 2
        instansi: unsri ilkom
    createoneuser+pesertarequest:
      title: createoneuser+pesertarequest
      required:
      - nama
      - email
      - no_hp
      - jenis_kelamin
      - tanggal_lahir
      - kelompok
      - instansi
      - jadwal_test
      - jenis_test
      type: object
      properties:
        nama:
          type: string
        email:
          type: string
        no_hp:
          type: string
        jenis_kelamin:
          type: string
        tanggal_lahir:
          type: string
        kelompok:
          type: string
        instansi:
          type: string
        jadwal_test:
          type: string
        jenis_test:
          type: array
          items:
            type: string
          description: ''
      example:
        nama: namaku
        email: tesKategori2@gmail.com
        no_hp: 08888188111
        jenis_kelamin: pria
        tanggal_lahir: 1997-10-13
        kelompok: BB
        instansi: ilkom
        jadwal_test: 1
        jenis_test:
        - IST
        - MII
    createpesertarequest:
      title: createpesertarequest
      required:
      - user_email
      - jadwal_test
      type: object
      properties:
        user_email:
          type: array
          items:
            type: string
          description: ''
        jadwal_test:
          type: integer
          format: int32
      example:
        user_email:
        - aa@gmail.com
        - b@gmail.com
        - c@gmail.com
        - dd@gmail.com
        jadwal_test: 3
    updatedatapesertabyidrequest:
      title: updatedatapesertabyidrequest
      required:
      - nama
      - email
      - no_hp
      - tanggal_lahir
      - kelompok
      - instansi
      - jenis_kelamin
      - password
      - valid
      - expired
      - jadwal_test
      - jenis_test
      type: object
      properties:
        nama:
          type: string
        email:
          type: string
        no_hp:
          type: string
        tanggal_lahir:
          type: string
        kelompok:
          type: string
        instansi:
          type: string
        jenis_kelamin:
          type: string
        password:
          type: string
        valid:
          type: string
        expired:
          type: string
        jadwal_test:
          type: integer
          format: int32
        jenis_test:
          type: array
          items:
            type: string
          description: ''
      example:
        nama: namaku
        email: tesKategori2@gmail.com
        no_hp: 08888188111
        tanggal_lahir: 1997-10-13
        kelompok: BB
        instansi: ilkom
        jenis_kelamin: pria
        password: ODUPWEWD
        valid: 2020-07-20T01:12:00Z
        expired: 2020-08-21T01:12:00Z
        jadwal_test: 1
        jenis_test:
        - IST
    createjadwaltestrequest:
      title: createjadwaltestrequest
      required:
      - waktu
      - expired
      - instansi
      - keterangan
      type: object
      properties:
        waktu:
          type: string
        expired:
          type: string
        instansi:
          type: string
        keterangan:
          type: string
      example:
        waktu: 2020-07-27 06:00
        expired: 2020-07-27 07:00
        instansi: testing 27
        keterangan: batch 1
    updatejadwaltestrequest:
      title: updatejadwaltestrequest
      required:
      - waktu
      - instansi
      type: object
      properties:
        waktu:
          type: string
        instansi:
          type: string
      example:
        waktu: 2020-07-19 10:00
        instansi: sma 9 testing
    createadminrequest:
      title: createadminrequest
      required:
      - name
      - email
      - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: Admin for delete
        email: del@educasia.id
        password: 11111111
    updateadminrequest:
      title: updateadminrequest
      required:
      - name
      - email
      - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: Admin testcreate update
        email: bbc@educasia.id
        password: 12341234
    loginadminrequest:
      title: loginadminrequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: ana@educasia.id
        password: 12345678
    resetpasswordadminbyuserrequest:
      title: resetpasswordadminbyuserrequest
      required:
      - old_password
      - new_password
      type: object
      properties:
        old_password:
          type: string
        new_password:
          type: string
      example:
        old_password: 1234567
        new_password: 12341234
    authpesertarequest:
      title: authpesertarequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: jhon@gmail.com
        password: 12345678
    submitjawabanrequest:
      title: submitjawabanrequest
      required:
      - jawaban_peserta
      - paket_soal
      - jenis_soal
      type: object
      properties:
        jawaban_peserta:
          type: array
          items:
            type: array
            items:
              type: integer
              format: int32
        paket_soal:
          type: string
        jenis_soal:
          type: string
      example:
        jawaban_peserta:
        - - 3
          - 5
        - - 2
          - 8
          - 0
        - - 2
          - 3
          - 5
        - - 2
          - 6
        - - 3
          - 0
        - - 7
          - 0
        - - 4
          - 5
        - - 4
          - 5
        - - 1
        - - 6
          - 7
        paket_soal: subtest_5_ist
        jenis_soal: ist
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
security:
- httpBearer: []
tags:
- name: users
- name: reset
- name: email
- name: peserta
- name: jadwal-test
  description: crud jadwal test
- name: admin
- name: export
- name: import
- name: Exam app
  description: ''